# Generated by Django 3.2.16 on 2023-01-19 08:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Parties Name')),
                ('party_initials', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Parties Initials')),
            ],
            options={
                'verbose_name': 'The Parties',
                'verbose_name_plural': 'The Parties',
            },
        ),
        migrations.CreateModel(
            name='Documentations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='List Number')),
                ('document_purpose', models.CharField(blank=True, max_length=300, null=True, verbose_name='Document Purpose')),
                ('document_author', models.CharField(blank=True, default='BUMANIK', max_length=30, null=True, verbose_name='Author')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Document Date')),
                ('document_upload', models.FileField(blank=True, null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('document_requestor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Requested By')),
                ('document_parties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='efiling.party')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archive',
            },
        ),
    ]
